/** Common lab tests for the African context. Can be replaced by LOINC API when integrating. */
export const COMMON_LAB_TESTS_AFRICA: { testName: string; testCode: string }[] = [
  { testName: "Full blood count (FBC)", testCode: "CBC" },
  { testName: "Malaria RDT", testCode: "MAL-RDT" },
  { testName: "Malaria blood smear", testCode: "MAL-SMEAR" },
  { testName: "HIV viral load", testCode: "HIV-VL" },
  { testName: "CD4 count", testCode: "CD4" },
  { testName: "HIV rapid test", testCode: "HIV-RAPID" },
  { testName: "Liver function tests (LFT)", testCode: "LFT" },
  { testName: "Renal function tests (RFT)", testCode: "RFT" },
  { testName: "Blood glucose (fasting)", testCode: "GLU-F" },
  { testName: "Blood glucose (random)", testCode: "GLU-R" },
  { testName: "HbA1c", testCode: "HBA1C" },
  { testName: "Urinalysis", testCode: "UA" },
  { testName: "Stool O&P", testCode: "STOOL-OP" },
  { testName: "TB GeneXpert", testCode: "TB-XPERT" },
  { testName: "Sputum AFB smear", testCode: "SPUTUM-AFB" },
  { testName: "Blood culture", testCode: "BLOOD-CULT" },
  { testName: "Urine culture", testCode: "URINE-CULT" },
  { testName: "Serum electrolytes (U&E)", testCode: "U&E" },
  { testName: "Lipid profile", testCode: "LIPID" },
  { testName: "TSH", testCode: "TSH" },
  { testName: "HBsAg", testCode: "HBSAG" },
  { testName: "HCV antibody", testCode: "HCV-AB" },
  { testName: "Pregnancy test (urine)", testCode: "HCG-U" },
  { testName: "Haemoglobin", testCode: "HB" },
  { testName: "Widal test", testCode: "WIDAL" },
];
