/**
 * Common medications for the African context (WHO Essential Medicines List–aligned).
 * Can be replaced by eEML (list.essentialmeds.org) export or API when available.
 */
export const COMMON_MEDICATIONS_AFRICA: string[] = [
  "Amoxicillin",
  "Amoxicillin-clavulanate",
  "Azithromycin",
  "Ceftriaxone",
  "Ciprofloxacin",
  "Metronidazole",
  "Doxycycline",
  "Co-trimoxazole",
  "Paracetamol",
  "Ibuprofen",
  "Metformin",
  "Glibenclamide",
  "Insulin (soluble)",
  "Insulin (NPH)",
  "Amlodipine",
  "Hydrochlorothiazide",
  "Losartan",
  "Enalapril",
  "Atenolol",
  "Omeprazole",
  "Salbutamol",
  "Beclometasone inhaler",
  "Prednisolone",
  "Dexamethasone",
  "Chloroquine",
  "Artemether-lumefantrine",
  "Quinine",
  "Artemether",
  "Efavirenz",
  "Lamivudine",
  "Tenofovir",
  "Dolutegravir",
  "Nevirapine",
  "Lopinavir-ritonavir",
  "Isoniazid",
  "Rifampicin",
  "Pyrazinamide",
  "Ethambutol",
  "Fluconazole",
  "Flucytosine",
  "Albendazole",
  "Praziquantel",
  "Ivermectin",
  "Ferrous sulfate",
  "Folic acid",
  "Zinc sulfate",
  "Oral rehydration salts (ORS)",
  "Vitamin A",
  "Magnesium sulfate",
  "Diazepam",
  "Carbamazepine",
  "Sodium valproate",
  "Phenytoin",
  "Amitriptyline",
  "Fluoxetine",
  "Haloperidol",
  "Chlorpromazine",
  "Morphine",
  "Tramadol",
  "Codeine",
  "Adrenaline (epinephrine)",
  "Hydrocortisone (IV)",
  "Calcium gluconate",
  "Naloxone",
];
